// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type CreateBook struct {
	Title       string     `json:"title"`
	Isbn        string     `json:"isbn"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
	PageCount   *int       `json:"pageCount,omitempty"`
	Edition     *int       `json:"edition,omitempty"`
	Authors     []uint     `json:"authors"`
	Publisher   *uint      `json:"publisher,omitempty"`
}

type CurrentUser struct {
	UUID       uuid.UUID         `json:"uuid"`
	Name       string            `json:"name"`
	Email      string            `json:"email"`
	Settings   *Settings         `json:"settings"`
	Lists      []*List           `json:"lists"`
	Collection []*CollectionItem `json:"collection"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateSettings struct {
	Private            bool `json:"private"`
	ShowName           bool `json:"showName"`
	ShowStats          bool `json:"showStats"`
	ShowCollection     bool `json:"showCollection"`
	ShowListsFollows   bool `json:"showListsFollows"`
	ShowAuthorsFollows bool `json:"showAuthorsFollows"`
}

type User struct {
	UUID       uuid.UUID         `json:"uuid"`
	Name       *string           `json:"name,omitempty"`
	Lists      []*List           `json:"lists,omitempty"`
	Collection []*CollectionItem `json:"collection,omitempty"`
}

type Status string

const (
	StatusToRead  Status = "TO_READ"
	StatusOnHold  Status = "ON_HOLD"
	StatusDropped Status = "DROPPED"
	StatusReading Status = "READING"
	StatusRead    Status = "READ"
)

var AllStatus = []Status{
	StatusToRead,
	StatusOnHold,
	StatusDropped,
	StatusReading,
	StatusRead,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusToRead, StatusOnHold, StatusDropped, StatusReading, StatusRead:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
