package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/marcos-brito/booklist/internal/models"
)

// AddToCollection is the resolver for the addToCollection field.
func (r *mutationResolver) AddToCollection(ctx context.Context, bookID string, status models.Status) (*models.CollectionItem, error) {
	panic(fmt.Errorf("not implemented: AddToCollection - addToCollection"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
