package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/marcos-brito/booklist/internal/models"
)

// Book is the resolver for the book field.
func (r *collectionItemResolver) Book(ctx context.Context, obj *models.CollectionItem) (*models.Book, error) {
}

// Collection is the resolver for the collection field.
func (r *profileResolver) Collection(ctx context.Context, obj *models.Profile) ([]*models.CollectionItem, error) {
}

// CollectionItem returns CollectionItemResolver implementation.
func (r *Resolver) CollectionItem() CollectionItemResolver { return &collectionItemResolver{r} }

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

type collectionItemResolver struct{ *Resolver }
type profileResolver struct{ *Resolver }
