name: Lint and format

on: 
  push:
    branches: 
      - "main"
  pull_request:

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        uses: golangci/golangci-lint-action@v6

  format-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        uses: actions/setup-go@v5
      - run: go fmt 
      - run: git diff --exit-code

  lint-deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno lint

  format-deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
      - run: deno fmt --check
